### PR TITLE
docs: add individual previews & regenerate preview

### LINKED ISSUE #8: Add/update preview images
## Description

This repository predates the updated template used in [catppuccin/template](https://github.com/catppuccin/template) so we should add preview images to the repository to be used in the README.

## Acceptance Criteria

1. The following images are added to the `assets` folder:
	- `latte.webp`
	- `frappe.webp`
	- `macchiato.webp`
	- `mocha.webp`
	- `preview.webp` generated by [catwalk](https://github.com/catppuccin/toolbox/tree/main/catwalk).
2. The `README.md` is updated to showcase the preview images.

### PR DESCRIPTION
**Pull request by ashish0kumar**
fixes #8

### CODE REVIEW

**Comment by ashish0kumar** [comment]
I would appreciate it if you could add the `hacktoberfest-accepted` label to my PR.

**Review by sgoudham — CHANGES_REQUESTED** [review]
Thanks for picking up the PR!

A bit of a nitpick but I see that it's misaligned a fair bit in some areas. I'd appreciate it if you could redo the screenshots and make sure the layout doesn't shift too much?

image

This repository (and 99% of other Catppuccin repositories) already have the `hacktoberfest` topic so your contribution will be counted 👍

**Comment by uncenter** [comment]
On Firefox you can use the "Take Screenshot" context menu > "Save visible" option to take a consistent screenshot:

CleanShot 2024-10-11 at 10 37 41

On other browsers you can go to the Developer Tools side panel, press Control + Shift + P to open the command bar, and run "Capture screenshot":

CleanShot 2024-10-11 at 10 39 48

**Comment by ashish0kumar** [comment]
redid the preview images, please review again

**Review by sgoudham — APPROVED** [review]
Thanks for updating the image!

**Pull request merged**
